pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

steps:
  - script: |
      docker build -t $(dockerId)/$(imageName) .
      docker login -u $(dockerId) -p $(dockerPassword)
      docker push $(dockerId)/$(imageName)