variables:
  dockerId: nodece  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: azure-test-go  # Replace with the name of the image you want to publish

pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

steps:
  - script: |
      docker build -t $(dockerId)/$(imageName) .
      docker login -u $(dockerId) -p $(dockerPassword)
      docker push $(dockerId)/$(imageName)